### ISSUE TITLE
Release new version with changes from PR #11

### ISSUE THREAD

**Issue by eze-kiel** [MatheSchool/typst-g-exam#12]
Hello,

First, thanks for your Typst package, I really like it and use it with pleasure :)

I recently opened a PR (#11) that got merged, but I do not think the change has been release in Typst Universe since.

![image](https://github.com/user-attachments/assets/3856fa85-1721-4d49-91bd-a1eafdd19c6f)

Would it be possible for you to do the release eventually?

Thanks a lot!

**Comment by andres-gimenez** [comment]
I've sent a version 0.3.1 with the changes you proposed. When the new version is approved by the typst team, it will be available.

**Comment by eze-kiel** [comment]
The packages are still in beta, they have an automatic review and then a manual one. I don't know how they will leave it in the final version.

**Comment by andres-gimenez** [comment]
The packages are still in beta, they have an automatic review and then a manual one. I don't know how they will leave it in the final version.
