### ISSUE TITLE
Indenting the entire question

### ISSUE THREAD

**Issue by Enivex** [MatheSchool/typst-g-exam#19]
Currently new lines in a question appears at the same level as the question number, and for sub-questions even to the left of the number (!). This isn't exactly ideal in my opinion, because it's less obvious where a question starts and stops.

![image](https://github.com/user-attachments/assets/83bf4ec9-c219-4d0d-887b-162ee85e3896)

![image](https://github.com/user-attachments/assets/7fb5da07-38fa-4292-83fe-75e3b5f13be6)

**Comment by andres-gimenez** [comment]
It looks better that way. But I have to check that it doesn't give problems, before publishing it.


![image](https://github.com/user-attachments/assets/f39c8151-0c8b-4e51-8eed-a3aa0cc6da2e)
