### ISSUE TITLE
Deprecation warnings in 0.12

### ISSUE THREAD

**Issue by Enivex** [MatheSchool/typst-g-exam#21]
While the template seems to still work, it triggers a ton of deprecation warnings in 0.12 due to its use of `locate()`.

**Comment by andres-gimenez** [comment]
> While the template seems to still work, it triggers a ton of deprecation warnings in 0.12 due to its use of `locate()`.

Thanks for the information. They've documented that they're going to remove the locate() functionality, but they don't say how to replace it.

**Comment by Enivex** [comment]
> > While the template seems to still work, it triggers a ton of deprecation warnings in 0.12 due to its use of `locate()`.
> 
> Thanks for the information. They've documented that they're going to remove the locate() functionality, but they don't say how to replace it.

The replacement is context https://typst.app/docs/reference/context/
